### ISSUE TITLE
Runtime error when running the demo walkthrough code

### ISSUE THREAD

**Issue by anhmoss** [korem-lab/DEBIAS-M#2]
Hello,

I was able to install DEBIAS-M and its dependencies on my Windows laptop, and then followed the provided demo walkthrough code to ensure that everything would run as expected.  When I ran the code `dmc.fit(X_train, y_train),`, it generated the following error message: _RuntimeError: expected scalar type Long but found Int_.   I attached a text file of the entire output message.  

Is there anything on my end that I could have missed during the installation process or along the demo code?   

Many thanks in advance. 

Sincerely,
Anh

[debiasm_output_message.txt](https://github.com/korem-lab/DEBIAS-M/files/15136754/debiasm_output_message.txt)

**Comment by gaustin15** [comment]
Thanks for sharing the output message; I just tried to run the example code in an environment similar to your error log's (python 3.8) but it ran through the example code without producing your error. Maybe the attached env file could help sidestep your issue. 
[debias-py38.txt](https://github.com/korem-lab/DEBIAS-M/files/15137171/debias-py38.txt)

Could you by any chance share your `conda list` output so that i can set up your exact environment? This error should be easy to resolve in the debias-m backend by specifying the right data type, but I'll need to test it in an env with the error.

**Comment by anhmoss** [comment]
Thanks for your prompt response! I'll go through the attached env file and see if that helps. In the meanwhile, here is my conda list output. 

Thanks again!
[condalist_anh.txt](https://github.com/korem-lab/DEBIAS-M/files/15139034/condalist_anh.txt)

**Comment by gaustin15** [comment]
Thank you for sharing the file. To confirm -- was this conda list for the env in which you obtained the data type error? I'm not seeing debias-m or pytorch-lightning in your file, so I would assume that this env would get an import error before reaching the data type issue.

**Comment by anhmoss** [comment]
Apologies about that -- you're right, I ended up not working in the conda environment since switching to the Spyder IDE (standalone installation version).

Here is the env list I am working out of: 
[piplist_anh.txt](https://github.com/korem-lab/DEBIAS-M/files/15139724/piplist_anh.txt)

**Comment by gaustin15** [comment]
Thanks again for sharing; it seems like that env is able to run on my machine.

Does the below code run successfully on yours? The piece of code that causes your error is running a similar syntax, I'm wondering if this might be what causes your issue.
```py
import numpy as np
import pandas as pd
import torch

n_samples = 96*5
n_batches = 5
n_features = 100
X = ( np.random.rand(n_samples, n_features) * 1000 ).astype(int)
batches = ( np.random.rand(n_samples) * n_batches ).astype(int)
X_with_batch = np.hstack((batches[:, np.newaxis], X))
x=torch.tensor(X_with_batch)
x[ x[:, 0].long() ]
```

**Comment by anhmoss** [comment]
No problem, thanks for checking it out. 

I ran the following code (assuming the rest would stay the same), and it still generated the same error message, which I also attached as a text file. 

```
import numpy as np
import pandas as pd
import torch

n_samples = 96*5
n_batches = 5
n_features = 100
X = ( np.random.rand(n_samples, n_features) * 1000 ).astype(int)
batches = ( np.random.rand(n_samples) * n_batches ).astype(int)
X_with_batch = np.hstack((batches[:, np.newaxis], X))
x=torch.tensor(X_with_batch)
x[ x[:, 0].long() ]

y = np.random.rand(n_samples)>0.5

X_with_batch[:5, :5]
y[:5]

val_inds = batches==4
X_train, X_val = X_with_batch[~val_inds], X_with_batch[val_inds]
y_train, y_val = y[~val_inds], y[val_inds]


y_train.shape
X_train.shape

dmc = DebiasMClassifier(x_val=X_val) ## give it the held-out inputs to account for
                                    ## those domains shifts while training

dmc.fit(X_train, y_train)
```
[error_message_04_27_2024.txt](https://github.com/korem-lab/DEBIAS-M/files/15140200/error_message_04_27_2024.txt)

**Comment by anhmoss** [comment]
Your fix to address the Windows-specific numpy issue cleared all error messages on my end --I was able to run the latest installation of DEBIAS-M on my Windows machine and ran the demo code with no issues. 

Thank you!

**Comment by gaustin15** [comment]
Thanks Anh!

For my own documentation purposes -- the error originated from a numpy issue (https://github.com/numpy/numpy/issues/17640) in which it wouldn't cast arrays to integers on windows machines. So, there was a section in the debias code that assumed the wrong dtype. 

This was fixed by specifying the dtype in torch (downstream of the numpy code), and was tested and validated using this repo's unit test pipeline on a Windows machine.
